"""Modified users

Revision ID: af2308c5c9d9
Revises: 8971da312157
Create Date: 2026-01-11 14:05:06.794100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af2308c5c9d9'
down_revision: Union[str, Sequence[str], None] = '8971da312157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum('admin', 'student', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('admin', 'student', name='userrole').create(op.get_bind())
    op.add_column('users', sa.Column('role', postgresql.ENUM('admin', 'student', name='userrole', create_type=False), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
